test_ht_strstr_exe = executable('test_ht_strstr',
			                    'ht_strstr_test.c',
			                    include_directories : inc,
			                    link_with : libhashtable)

test_ht_strint_exe = executable('test_ht_strint',
			                    'ht_strint_test.c',
			                    include_directories : inc,
			                    link_with : libhashtable)

test_ht_strfloat_exe = executable('test_ht_strfloat',
			                      'ht_strfloat_test.c',
			                      include_directories : inc,
			                      link_with : libhashtable)

test_ht_strdouble_exe = executable('test_ht_strdouble',
			                       'ht_strdouble_test.c',
			                       include_directories : inc,
			                       link_with : libhashtable)

test_ht_fnv1a_collision_exe = \
  executable('test_ht_fnv1a_collision',
             'ht_fnv1a_collision_test.c',
             include_directories: inc,
             link_with: libhashtable)

test_ht_random_exe = executable('test_ht_random',
			                    'ht_random_test.c',
			                    include_directories : inc,
			                    link_with : libhashtable)

test_ht_int_exe = executable('test_ht_int',
			                 'ht_int_test.c',
			                 include_directories : inc,
			                 link_with : libhashtable)

test_ht_bulk_exe = executable('test_ht_bulk',
			                  'ht_bulk_test.c',
			                  include_directories : inc,
			                  link_with : libhashtable)

test_ht_siphash_exe = executable('test_ht_siphash',
			                     'ht_siphash_test.c',
			                     include_directories : inc,
			                     link_with : libhashtable)

test_ht_keyed_exe = executable('test_ht_keyed',
			                   'ht_keyed_test.c',
			                   include_directories : inc,
			                   link_with : libhashtable)

test_ht_ops_exe = executable('test_ht_ops',
			                 'ht_ops_test.c',
			                 include_directories : inc,
			                 link_with : libhashtable)

test_ht_strblob_exe = executable('test_ht_strblob',
			                     'ht_strblob_test.c',
			                     include_directories : inc,
			                     link_with : libhashtable)

test_ht_u64ptr_exe = executable('test_ht_u64ptr',
			                    'ht_u64ptr_test.c',
			                    include_directories : inc,
			                    link_with : libhashtable)

test_ht_u64blob_exe = executable('test_ht_u64blob',
			                     'ht_u64blob_test.c',
			                     include_directories : inc,
			                     link_with : libhashtable)

test_ht_strptr_exe = executable('test_ht_strptr',
			                    'ht_strptr_test.c',
			                    include_directories : inc,
			                    link_with : libhashtable)

test('libhashtable', test_ht_strstr_exe)
test('libhashtable', test_ht_strint_exe)
test('libhashtable', test_ht_strfloat_exe)
test('libhashtable', test_ht_strdouble_exe)
test('libhashtable', test_ht_fnv1a_collision_exe)
test('libhashtable', test_ht_random_exe)
test('libhashtable', test_ht_int_exe)
test('libhashtable', test_ht_bulk_exe)
test('libhashtable', test_ht_siphash_exe)
test('libhashtable', test_ht_keyed_exe)
test('libhashtable', test_ht_ops_exe)
test('libhashtable', test_ht_strblob_exe)
test('libhashtable', test_ht_u64ptr_exe)
test('libhashtable', test_ht_u64blob_exe)
test('libhashtable', test_ht_strptr_exe)
